package stannieman.rest;

public enum RestClientResultCodes {
    REQUEST_TIMED_OUT,
    REQUEST_FAILED,
    REQUEST_INTERRUPTED,
    RESPONSE_IS_NOT_VALID_JSON,
    JSON_RESPONSE_DATA_TYPE_MISMATCH,
    JSON_ERROR_DATA_TYPE_MISMATCH,
    CANNOT_CREATE_OBJECT_FROM_SUCCESS_RESPONSE,
    CANNOT_CREATE_OBJECT_FROM_ERROR_RESPONSE,
    CANNOT_CREATE_JSON_STRING_FROM_OBJECT,
    CANNOT_CREATE_URI
}
